TestSuite@{
	"Element.mt",
	"Equal.mt",
	"mapAtElems.mt",
	"setMake_abstruct.mt",
	"setMake_callWithOptions.mt",
	"setMake_general.mt",
	"setMake_immediate.mt",
	"singletonQ.mt",
	"Subsets.mt",
	"Union.mt"}